# -----------------------------------------------------------------------------
#
# This file contains tasks related to configuring installation of Docker
# and relevant plugins for an Debian based system.
#
# -----------------------------------------------------------------------------

- name: "HTH | Docker | Debian | Set signing key path"
  ansible.builtin.set_fact:
    hth_docker_signing_key_path: "{{ hth_docker_repository_signing_key_directory_path }}/{{ hth_docker_repository_signing_key_filename }}"
  when:
    - docker.signing is defined

- name: "HTH | Docker | Debian | Copy signing key"
  ansible.builtin.copy:
    src: "{{ docker.signing.key }}"
    dest: "{{ hth_docker_signing_key_path }}"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - docker.signing is defined
    - docker.remove is undefined or not docker.remove

- name: "HTH | Docker | Debian | Add official repository"
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: ["https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"]
    signed_by: "{{ hth_docker_signing_key_path | default('https://download.docker.com/linux/' + ansible_facts['distribution'] | lower + '/gpg') }}"
    suites: ["{{ ansible_facts['distribution_release'] }}"]
    components: [stable]
    state: "{{ 'absent' if docker.remove is defined and docker.remove else 'present' }}"
    enabled: true
  register: docker_repo_state

- name: "HTH | Docker | Debian | Prioritize repository"
  ansible.builtin.copy:
    src: priority
    dest: "{{ hth_docker_apt_priority_file_path }}"
    owner: root
    group: root
    mode: 0644
  when:
    - docker.remove is undefined or not docker.remove
    - docker.priority is defined
    - docker.priority

- name: "HTH | Docker | Debian | Update apt"
  ansible.builtin.apt:
    update_cache: yes
  when:
    - docker_repo_state.changed

- name: "HTH | Docker | Debian | Manage Docker package"
  ansible.builtin.apt:
    name: "{{ hth_docker_package_name + '=' + docker.version if docker.version is defined and docker.version != 'latest' else hth_docker_package_name }}"
    state: >-
      {{ 'absent' if docker.remove is defined and docker.remove
          else 'present' if docker.version is defined and docker.version != 'latest'
          else 'latest' }}

- name: "HTH | Docker | Debian | Manage Docker Compose package"
  ansible.builtin.apt:
    name: "{{ hth_docker_compose_package_name }}"
    state: >-
      {{ 'absent' if (docker.compose.remove is defined and docker.compose.remove) or (docker.remove is defined and docker.remove)
          else 'latest' }}
  when:
    - docker.compose is defined or (docker.remove is defined and docker.remove)

- name: "HTH | Docker | Debian | Remove signing key"
  ansible.builtin.file:
    path: "{{ hth_docker_signing_key_path }}"
    state: absent
  when:
    - hth_docker_signing_key_path is defined
    - docker.remove is defined
    - docker.remove

- name: "HTH | Docker | Debian | Remove repository prioritization"
  ansible.builtin.file:
    path: "{{ hth_docker_apt_priority_file_path }}"
    state: absent
  when:
    - docker.remove is defined
    - docker.remove
