# -----------------------------------------------------------------------------
#
# This file contains tasks related to configuring installation of Docker
# and relevant plugins for an Debian based system.
#
# -----------------------------------------------------------------------------

- name: "Docker | Debian | Add official repository"
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: ["https://download.docker.com/linux/{{ ansible_distribution | lower }}"]
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    state: "{{ 'absent' if docker.remove is defined and docker.remove else 'present' }}"
    enabled: true
  register: docker_repo_state

- name: "Docker | Debian | Update apt"
  ansible.builtin.apt:
    update_cache: yes
  when:
    - docker_repo_state.changed

- name: "Docker | Debian | Manage 'docker-ce' package"
  ansible.builtin.apt:
    name: "{{ 'docker-ce=' + docker.version if docker.version is defined and docker.version != 'latest' else 'docker-ce' }}"
    state: >-
      {{ 'absent' if docker.remove is defined and docker.remove
          else 'present' if docker.version is defined and docker.version != 'latest'
          else 'latest' }}

- name: "Docker | Debian | Manage 'docker-compose-plugin' package"
  ansible.builtin.apt:
    name: "{{ 'docker-compose-plugin=' + docker.compose.version if docker.compose.version is defined and docker.compose.version != 'latest' else 'docker-compose-plugin'}}"
    state: >-
      {{ 'absent' if docker.compose.remove is defined and docker.remove
          else 'present' if docker.compose.version is defined and docker.compose.version != 'latest'
          else 'latest' }}
  when:
    - docker.compose is defined
