# -----------------------------------------------------------------------------
#
# This file is entry file into the Docker engine installation process.
#
# -----------------------------------------------------------------------------

- name: "Docker | Install | Install Docker for Debian systems"
  ansible.builtin.include_tasks: debian.yml
  when:
    - ansible_distribution in ["Ubuntu", "Debian"]
