---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
  - role: hth.docker
    vars:
      docker:
        version: latest
        priority: true
        compose:
          version: latest
