- name: docker | assert | validate input config
  ansible.utils.validate:
    data: "{{ docker }}"
    criteria: "{{ lookup('file', 'assertions/criteria/docker-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "Docker | Install"
  ansible.builtin.include_tasks: install/main.yml

- name: "Docker | Compose | Configure"
  ansible.builtin.include_tasks: compose/main.yml
  when:
    - docker.compose is defined
