- name: docker | assert | validate input config
  ansible.utils.validate:
    data: "{{ docker }}"
    criteria: "{{ lookup('file', 'assertions/criteria/docker-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  when:
    - docker is defined

- name: docker | install
  ansible.builtin.include_tasks: install/main.yml

- name: docker | compose
  ansible.builtin.include_tasks: compose/main.yml
  when:
    - docker.compose is defined
