---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
  - role: hth.docker
    vars:
      docker:
        version: "5:29.6.0-1~ubuntu.24.04~noble"
        priority: true
        compose:
          version: "5.1.4-1~ubuntu.24.04~noble"
