- name: Prepare for role testing
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      tags: system,utilities
      ansible.builtin.apt:
        update_cache: yes

    - name: install python3-debian (needed for the 'deb822_repository' task)
      apt:
        name: python3-debian
        state: latest
      when: ansible_facts['os_family'] == 'Debian'

  roles:
  - role: hth.docker
    vars:
      secret_variable: "a secret variable"
      docker:
        version: latest
        compose:
          compositions:
            - name: "preparing-for-secret-removal"
              source: "docker-compose.yml"
              destination: "/srv/testing-removal"
              secrets:
                - name: "secret-value"
                  value: "a secret value"
                - name: "secret-variable"
                  variable: "secret_variable"
