# -----------------------------------------------------------------------------
#
# This file contains tasks related to managing environment variables under
# a specific path.
#
# -----------------------------------------------------------------------------

- name: "HTH | Docker | Environment | Set directory path"
  ansible.builtin.set_fact:
    environment_path: "{{ project_dir }}{{ '/' ~ env.path if env.path | default('') | length > 0 else '' }}"

- name: "HTH | Docker | Environment | Create directory"
  ansible.builtin.file:
    path: "{{ environment_path }}"
    owner: "{{ env.owner | default(composition.user | default('root')) }}"
    group: "{{ env.group | default(composition.group | default('root')) }}"
    modification_time: "preserve"
    access_time: "preserve"
    state: "directory"
    recurse: true
  when:
    - env.remove is not defined or not env.remove

- name: "HTH | Docker | Environment | Set file path"
  ansible.builtin.set_fact:
    environment_file: "{{ environment_path }}/.env"

- name: "HTH | Docker | Environment | Create file"
  ansible.builtin.file:
    path: "{{ environment_file }}"
    state: "touch"
    owner: "{{ env.owner | default(composition.user | default('root')) }}"
    group: "{{ env.group | default(composition.group | default('root')) }}"
    modification_time: "preserve"
    access_time: "preserve"
    mode: "{{ env.mode | default('0644')}}"
  when:
    - env.remove is not defined or not env.remove

- name: "HTH | Docker | Environment | Manage entries"
  ansible.builtin.include_tasks: variable.yml
  loop: "{{ env.entries }}"
  loop_control:
    loop_var: entry
  when:
    - env.remove is not defined or not env.remove

- name: "HTH | Docker | Environment | Remove file"
  ansible.builtin.file:
    path: "{{ environment_file }}"
    state: "absent"
  when:
    - env.remove is defined
    - env.remove
