# -----------------------------------------------------------------------------
#
# This file contains tasks related to managing Docker environment variables.
#
# -----------------------------------------------------------------------------

- name: "docker | environment | manage environments"
  ansible.builtin.include_tasks: environment.yml
  loop: "{{ composition.environments }}"
  loop_control:
    loop_var: env
