# -----------------------------------------------------------------------------
#
# This file contains tasks related to adding Docker environment variables.
# It expects a dict named 'env' to be present.
#
# -----------------------------------------------------------------------------

- name: "docker | env | set environment variable from value"
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/.env"
    regexp: "^{{ env.name }}="
    line: "{{ env.name }}='{{ env.value }}'"
  when:
    - env.remove is not defined or not env.remove
    - env.value is defined

- name: "docker | env | set environment variable from variable"
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/.env"
    regexp: "^{{ env.name }}="
    line: "{{ env.name }}='{{ lookup('vars', env.variable) }}'"
  when:
    - env.remove is not defined or not env.remove
    - env.variable is defined

- name: "docker | env | remove environment variable"
  ansible.builtin.lineinfile:
     path: "{{ project_dir }}/.env"
     regexp: "^{{ env.name }}="
     state: "absent"
  when:
    - env.remove is defined and env.remove
