- name: Prepare for role testing
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      tags: system,utilities
      ansible.builtin.apt:
        update_cache: yes

    - name: install python3-debian (needed for the 'deb822_repository' task)
      apt:
        name: python3-debian
        state: latest
      when: ansible_facts['os_family'] == 'Debian'

  roles:
  - role: hth.docker
    vars:
      docker:
        version: latest
