# -----------------------------------------------------------------------------
#
# This file contains tasks related to copying over, configuring and running
# a composition. It expects to find a dict object called 'composition'.
#
# -----------------------------------------------------------------------------

- name: docker | compose | composition path
  ansible.builtin.set_fact:
    project_dir: "{{ composition.destination if composition.destination is defined else '/srv/' + composition.name }}"

- name: docker | compose | create composition directory
  ansible.builtin.file:
    path: "{{ project_dir }}"
    owner: "{{ composition.user | default('root') }}"
    group: "{{ composition.group | default('root') }}"
    mode: "{{ composition.mode | default('0755') }}"
    state: "{{ 'absent' if composition.remove is defined and composition.remove else 'directory' }}"

- name: docker | compose | copy compose file
  ansible.builtin.copy:
    src: "{{ composition.source }}"
    dest: "{{ project_dir }}"
    force: "{{ composition.force | default(false) }}"
    owner: "{{ composition.user | default('root') }}"
    group: "{{ composition.group | default('root') }}"
    mode: "{{ composition.mode | default('0644') }}"
  when:
    - composition.remove is not defined or not composition.remove

- name: docker | compose | manage secrets
  ansible.builtin.include_tasks: secrets.yml
  loop: "{{ composition.secrets }}"
  loop_control:
    loop_var: secret
  when:
    - composition.secrets is defined
    - composition.remove is not defined or not composition.remove
