# -----------------------------------------------------------------------------
#
# This file contains tasks related to copying over, configuring and running
# a composition. It expects to find a dict object called 'composition'.
#
# -----------------------------------------------------------------------------

- name: docker | compose | create composition destination
  ansible.builtin.file:
    path: "{{ composition.destination }}"
    owner: "{{ composition.user | default('root') }}"
    group: "{{ composition.group | default('root') }}"
    mode: "{{ composition.mode | default('0755') }}"
    state: "{{ 'absent' if composition.remove is defined and composition.remove else 'directory' }}"

- name: docker | compose | copy compose file
  ansible.builtin.copy:
    src: "{{ composition.source }}"
    dest: "{{ composition.destination }}"
    force: "{{ composition.force | default(false) }}"
    owner: "{{ composition.user | default('root') }}"
    group: "{{ composition.group | default('root') }}"
    mode: "{{ composition.mode | default('0644') }}"
  when:
    - composition.remove is not defined or not composition.remove
