# -----------------------------------------------------------------------------
#
# This file contains tasks related to configuring paths for extra files.
#
# It expects to find  a dict object called 'composition' and a string
# called 'project_dir'.
#
# -----------------------------------------------------------------------------

- name: "docker | extras | manage destinations"
  ansible.builtin.include_tasks: path.yml

- name: "docker | extras | copy extra source"
  ansible.builtin.copy:
    src: "{{ extra.source }}"
    dest: "{{ project_dir }}/{{ extra.destination.path }}"
    owner: "{{ extra.owner | default(composition.owner | default('root')) }}"
    group: "{{ extra.group | default(composition.group | default('root')) }}"
    mode: "{{ extra.mode | default('0755') }}"
    force: "{{ extra.force | default(false) }}"
  when:
    - extra.source is defined
