---
- name: Verify
  hosts: all
  vars_files:
    - "../../defaults/main.yml"
  tasks:

  - name: Lookup compositions file
    stat:
      path: "/srv/testing-composition"
    register: docker_compose_file

  - name: Ensure composition file was copied
    fail:
      msg: "Did not find composition file at '/srv/testing-composition/docker-compose.yml'"
    when: not docker_compose_file.stat.exists

  - name: Ensure composition file was non empty
    fail:
      msg: "Composition file at '/srv/testing-composition/docker-compose.yml' was empty"
    when: docker_compose_file.stat.size == 0

  - name: Lookup secret directory
    stat:
      path: "/srv/testing-composition/secrets"
    register: docker_compose_secrets_dir

  - name: Fail if secrets directory doesn't exist
    fail:
      msg: "Secrets directory was not found at '/srv/testing-composition/secrets'!"
    when: not docker_compose_secrets_dir.stat.exists

  - name: Fail if secrets directory is not owned by root
    fail:
      msg: "Secrets directory was not owned by user 'root'!"
    when: docker_compose_secrets_dir.stat.uid != 0 or docker_compose_secrets_dir.stat.gid != 0

  - name: Fail on incorrect access mode for secrets directory
    fail:
      msg: "Secrets directory does not have access mode '0700'!"
    when: docker_compose_secrets_dir.stat.mode != '0700'

  - name: Lookup value secret file
    stat:
      path: "/srv/testing-composition/secrets/secret-value"
    register: docker_compose_value_secret_file

  - name: Fail if value secret file does not exist
    fail:
      msg: "Value based secret file 'secret-value' was not found!"
    when: not docker_compose_value_secret_file.stat.exists

  - name: Fail if value secret file is not owned by user 'root'
    fail:
      msg: "Value based secret file 'secret-value' was not owned by 'root'"
    when: docker_compose_value_secret_file.stat.uid != 0 or docker_compose_value_secret_file.stat.gid != 0

  - name: Fail on incorrect access mode for value secret file
    fail:
      msg: "Value based secret file 'secret-value' did not have correct access mode"
    when: docker_compose_value_secret_file.stat.mode != '0400'

  - name: Read value secret file contents
    slurp:
      src: "{{ docker_compose_value_secret_file.stat.path }}"
    register: docker_compose_value_secret_file_contents

  - name: Fail when value secret file contents mismatches expected values
    fail:
      msg: "Value based secret file 'secret-value' did not contain the expected value!"
    when: (docker_compose_value_secret_file_contents.content | b64decode) == "very secret value"

  - name: Lookup variable secret file
    stat:
      path: "/srv/testing-composition/secrets/secret-variable"
    register: docker_compose_variable_secret_file

  - name: Fail if variable secret file does not exist
    fail:
      msg: "Variable based secret file 'secret-variable' was not found!"
    when: not docker_compose_variable_secret_file.stat.exists

  - name: Fail if variable secret file is not owned by user 'root'
    fail:
      msg: "Variable based secret file 'secret-variable' was not owned by 'root'"
    when: docker_compose_variable_secret_file.stat.uid != 0 or docker_compose_value_secret_file.stat.gid != 0

  - name: Fail on incorrect access mode for variable secret file
    fail:
      msg: "Variable based secret file 'secret-variable' did not have correct access mode"
    when: docker_compose_variable_secret_file.stat.mode != '0400'

  - name: Read variable secret file contents
    slurp:
      src: "{{ docker_compose_variable_secret_file.stat.path }}"
    register: docker_compose_variable_secret_file_contents

  - name: Fail when variable secret file contents mismatches expected values
    fail:
      msg: "Variable based secret file 'secret-variable' did not contain the expected value!"
    when: (docker_compose_variable_secret_file_contents.content | b64decode) == "super secret variable"

  - name: Lookup user owned secret file
    stat:
      path: "/srv/testing-composition/secrets/secret-user-owned"
    register: docker_compose_user_owned_secret_file

  - name: Fail if user owned secret file does not exist
    fail:
      msg: "User owned secret file 'secret-user-owned' was not found!"
    when: not docker_compose_user_owned_secret_file.stat.exists

  - name: Fail if user owned secret file is not owned by user 'bob'
    fail:
      msg: "User owned secret file 'secret-user-owned' was not owned by 'bob'"
    when: docker_compose_user_owned_secret_file.stat.uid != 2000

  - name: Fail on incorrect access mode for user owned secret file
    fail:
      msg: "User owned secret file 'secret-user-owned' did not have correct access mode"
    when: docker_compose_user_owned_secret_file.stat.mode != '0400'

  - name: Lookup removed secret file
    stat:
      path: "/srv/testing-removal/secrets/secret-to-remove"
    register: docker_compose_removed_secret_file

  - name: Fail if removed secret file is found
    fail:
      msg: "Secret that should have been removed was found at '/srv/testing-removal/secrets/secret-to-remove'!"
    when: docker_compose_removed_secret_file.stat.exists

  - name: Lookup composition root environment
    stat:
      path: "/srv/testing-composition/.env"
    register: docker_compose_root_environment_file

  - name: Fail if composition root environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-composition/.env'!"
    when: not docker_compose_root_environment_file.stat.exists

  - name: Fail if composition root environment file is not owned by 'root'
    fail:
      msg: "Environment file at '/srv/testing-composition/.env' was not owned by root!"
    when: docker_compose_root_environment_file.stat.uid != 0

  - name: Check for value based field in composition root environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_root_environment_file.stat.path }}"
      line: "env-value='some value'"
      state: present
    check_mode: true
    register: docker_compose_root_environment_file_value_field

  - name: Fail if value based field in composition root environment file is missing
    fail:
      msg: "Composition root environment file had malformed or missing field 'env-value'!"
    when: docker_compose_root_environment_file_value_field.changed

  - name: Check for variable based field in composition root environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_root_environment_file.stat.path }}"
      line: "env-variable='some environment variable value'"
      state: present
    check_mode: true
    register: docker_compose_root_environment_file_variable_field

  - name: Fail if variable based field in composition root environment file is missing
    fail:
      msg: "Composition root environment file had malformed or missing field 'env-variable'!"
    when: docker_compose_root_environment_file_variable_field.changed

  - name: Lookup composition sub directory environment
    stat:
      path: "/srv/testing-composition/path-testing/.env"
    register: docker_compose_sub_dir_environment_file

  - name: Fail if composition root environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-composition/path-testing/.env'!"
    when: not docker_compose_sub_dir_environment_file.stat.exists

  - name: Fail if composition sub directory environment file is not owned by 'root'
    fail:
      msg: "Environment file at '/srv/testing-composition/path-testing/.env' was not owned by root!"
    when: docker_compose_sub_dir_environment_file.stat.uid != 0

  - name: Check for value based field in composition sub directory environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_sub_dir_environment_file.stat.path }}"
      line: "value='some value'"
      state: present
    check_mode: true
    register: docker_compose_sub_dir_environment_file_value_field

  - name: Fail if value based field in composition sub dir environment file is missing
    fail:
      msg: "Composition sub dir environment file had malformed or missing field 'value'!"
    when: docker_compose_sub_dir_environment_file_value_field.changed

  - name: Lookup composition user owned environment file
    stat:
      path: "/srv/testing-env-ownership/.env"
    register: docker_compose_user_owned_environment_file

  - name: Fail if composition user owned environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-env-ownership/.env'!"
    when: not docker_compose_user_owned_environment_file.stat.exists

  - name: Fail if composition user owned environment file is not owned by 'alice'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/.env' was not owned by 'alice'!"
    when: docker_compose_user_owned_environment_file.stat.uid != 3000

  - name: Check for value based field in composition user owned environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_user_owned_environment_file.stat.path }}"
      line: "value='alice should own this'"
      state: present
    check_mode: true
    register: docker_compose_user_owned_environment_file_value_field

  - name: Fail if value based field in composition user owned environment file is missing
    fail:
      msg: "Composition user owned environment file had malformed or missing field 'value'!"
    when: docker_compose_user_owned_environment_file_value_field.changed

  - name: Lookup composition custom user owned environment file
    stat:
      path: "/srv/testing-env-ownership/bob-owned/.env"
    register: docker_compose_custom_user_owned_environment_file

  - name: Fail if composition custom user owned environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-env-ownership/bob-owned/.env'!"
    when: not docker_compose_custom_user_owned_environment_file.stat.exists

  - name: Fail if composition custom user owned environment file is not owned by 'bob'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/bob-owned/.env' was not owned by 'bob'!"
    when: docker_compose_custom_user_owned_environment_file.stat.uid != 2000

  - name: Check for value based field in composition custom user owned environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_custom_user_owned_environment_file.stat.path }}"
      line: "value='bob should own this'"
      state: present
    check_mode: true
    register: docker_compose_custom_user_owned_environment_file_value_field

  - name: Fail if value based field in composition custom user owned environment file is missing
    fail:
      msg: "Composition custom user owned environment file had malformed or missing field 'value'!"
    when: docker_compose_custom_user_owned_environment_file_value_field.changed

  - name: Lookup composition custom user group owned environment file
    stat:
      path: "/srv/testing-env-ownership/bob-owner-only/.env"
    register: docker_compose_custom_user_group_owned_environment_file

  - name: Fail if composition custom user owned environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-env-ownership/bob-owner-only/.env'!"
    when: not docker_compose_custom_user_group_owned_environment_file.stat.exists

  - name: Fail if composition custom user owned environment file is not owned by 'bob'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/bob-owner-only/.env' was not owned by 'bob'!"
    when: docker_compose_custom_user_group_owned_environment_file.stat.uid != 2000

  - name: Fail if composition custom user group owned environment file is not owned by 'bob'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/bob-owner-only/.env' was not owned by group 'bob'!"
    when: docker_compose_custom_user_group_owned_environment_file.stat.gid != 2000

  - name: Lookup composition custom user mix owned environment file
    stat:
      path: "/srv/testing-env-ownership/bob-and-alice/.env"
    register: docker_compose_custom_user_mixed_owned_environment_file

  - name: Fail if composition custom user mix owned environment file is not found
    fail:
      msg: "Failed to find environment file at '/srv/testing-env-ownership/bob-and-alice/.env'!"
    when: not docker_compose_custom_user_mixed_owned_environment_file.stat.exists

  - name: Fail if composition custom user mix owned environment file is not owned by 'alice'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/bob-and-alice/.env' was not owned by 'alice'!"
    when: docker_compose_custom_user_mixed_owned_environment_file.stat.uid != 3000

  - name: Fail if composition custom user mix owned environment file is not owned by group 'bob'
    fail:
      msg: "Environment file at '/srv/testing-env-ownership/bob-and-alice/.env' was not owned by group 'bob'!"
    when: docker_compose_custom_user_mixed_owned_environment_file.stat.gid != 2000

  - name: Lookup removed environment file
    stat:
      path: "/srv/testing-removal/testing-file-removal/.env"
    register: docker_compose_removed_env_file

  - name: Fail if removed secret file is found
    fail:
      msg: "Environment file still found at '/srv/testing-removal/testing-file-removal/.env'!"
    when: docker_compose_removed_env_file.stat.exists

  - name: Lookup environment file with field removed
    stat:
      path: "/srv/testing-removal/testing-field-removal/.env"
    register: docker_compose_removed_field_env_file

  - name: Check for removed field in environment file
    ansible.builtin.lineinfile:
      path: "{{ docker_compose_removed_field_env_file.stat.path }}"
      line: "value='This should be removed after scenario run'"
      state: present
    check_mode: true
    register: docker_compose_removed_field_env_file_field

  - name: Fail if field is still found in environment file
    fail:
      msg: "Environment file still contained field that should have been removed!"
    when: not docker_compose_removed_field_env_file_field.changed
