# -----------------------------------------------------------------------------
#
# This file contains tasks related to adding Docker secrets.
# It expects a dict named 'secrets' to be present.
#
# -----------------------------------------------------------------------------

- name: "HTH | Docker | Secrets | Manage secret file"
  ansible.builtin.file:
    path: "{{ project_dir }}/secrets/{{ secret.name }}"
    state: "{{ 'absent' if secret.remove is defined and secret.remove else 'touch' }}"
    owner: "{{ secret.owner if (secret.owner is defined) else 'root' }}"
    group: "{{ secret.owner if (secret.owner is defined) else 'root' }}"
    modification_time: preserve
    access_time: preserve
    mode: "0400"

- name: "HTH | Docker | Secrets | Set secret value as file content"
  ansible.builtin.copy:
    dest: "{{ project_dir }}/secrets/{{ secret.name }}"
    content: "{{ secret.value | trim }}"
    mode: "0600"
    force: false
  no_log: true
  when:
    - secret.remove is not defined or not secret.remove
    - secret.value is defined

- name: "HTH | Docker | Secrets | Set secret variable as file content"
  ansible.builtin.copy:
    dest: "{{ project_dir }}/secrets/{{ secret.name }}"
    content: "{{ lookup('vars', secret.variable) | trim }}"
    mode: "0600"
    force: false
  no_log: true
  when:
    - secret.remove is not defined or not secret.remove
    - secret.variable is defined
