# -----------------------------------------------------------------------------
#
# This file contains tasks related to adding Docker secrets.
# It expects a dict named 'secrets' to be present.
#
# -----------------------------------------------------------------------------

- name: "docker | secrets | manage secret file"
  ansible.builtin.file:
    path: "{{ project_dir }}/secrets/{{ secret.name }}"
    state: "{{ 'absent' if secret.remove is defined and secret.remove else 'touch' }}"
    modification_time: preserve
    access_time: preserve
    owner: "root"
    group: "root"
    mode: "0600"

- name: "docker | secrets | set secret value as file content"
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/secrets/{{ secret.name }}"
    regexp: "^"
    line: "{{ secret.value }}"
  no_log: true
  when:
    - secret.remove is not defined or not secret.remove
    - secret.value is defined

- name: "docker | secrets | set secret variable as file content"
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/secrets/{{ secret.name }}"
    regexp: "^"
    line: "{{ lookup('vars', secret.variable) }}"
  no_log: true
  when:
    - secret.remove is not defined or not secret.remove
    - secret.variable is defined
