# -----------------------------------------------------------------------------
#
# This file contains tasks related to managing Docker secrets.
#
# -----------------------------------------------------------------------------

- name: "docker | secrets | create secrets directory"
  ansible.builtin.file:
    path: "{{ project_dir }}/secrets"
    state: directory
    owner: "root"
    group: "root"
    mode: "0700"

- name: "docker | secrets | add secret"
  ansible.builtin.include_tasks: add_secret.yml
  loop: "{{ composition.secrets }}"
  loop_control:
    loop_var: secret
  when:
    - composition.secrets is defined
